# Generated by Django 5.0.4 on 2024-06-06 08:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('leave_days', models.IntegerField(default=0)),
                ('off_days', models.IntegerField(default=0)),
                ('job_group', models.CharField(max_length=255)),
                ('contract_renewal_requested', models.BooleanField(default=False)),
                ('contract_renewal_date', models.DateField(blank=True, null=True)),
                ('benefits', models.ManyToManyField(to='human.benefit')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='human_employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_group', models.CharField(choices=[('Junior Staff', 'Junior Staff'), ('Supervisor', 'Supervisor'), ('Junior Manager', 'Junior Manager'), ('Middle Manager', 'Middle Manager'), ('Senior Manager', 'Senior Manager'), ('Intern', 'Intern')], default='Junior Staff', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_id', models.UUIDField(default=uuid.uuid4)),
                ('department', models.CharField(choices=[('Network', 'Network & Cloud Development'), ('Programming', 'Programming'), ('Cyber security', 'Cyber Security'), ('AI', 'Artificial Inteligence'), ('Finance & Accounts', 'Finance & Accounts'), ('Sales & Marketing', 'Sales & Marketing'), ('Research & Development', 'Research & Development'), ('Customer Support', 'Customer Support'), ('Projects Development', 'Projects Development'), ('Faculty of Education', 'Faculty of Education'), ('Faculty of Science', 'Faculty of Science'), ('Faculty of Agriculture', 'Faculty of Agriculture'), ('Faculty of Computer Engineering', 'Faculty of Computer Engineering'), ('Faculty of Mechanical Engineering', 'Faculty of Mechanical Engineering'), ('Faculty of Civil Engineering', 'Faculty of Civil Engineering'), ('Faculty of Science & Technology', 'Faculty of Science & Technology'), ('Faculty of Law', 'Faculty of Law'), ('Faculty of Business Management', 'Faculty of Business Management')], default='', max_length=50)),
                ('reason', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Declined', 'Declined'), ('Accepted', 'Accepted')], default='Pending', max_length=20)),
                ('hr_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('warning', 'Warning Letter'), ('appraisal', 'Appraisal Letter'), ('recommendation', 'Recommendation Letter'), ('contract_award', 'Contract Award Letter'), ('contract_renewal', 'Contract Renewal Letter'), ('contract_end', 'Contract End Letter')], max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Offday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offday_id', models.UUIDField(default=uuid.uuid4)),
                ('department', models.CharField(choices=[('Network', 'Network & Cloud Development'), ('Programming', 'Programming'), ('Cyber security', 'Cyber Security'), ('AI', 'Artificial Inteligence'), ('Finance & Accounts', 'Finance & Accounts'), ('Sales & Marketing', 'Sales & Marketing'), ('Research & Development', 'Research & Development'), ('Customer Support', 'Customer Support'), ('Projects Development', 'Projects Development'), ('Faculty of Education', 'Faculty of Education'), ('Faculty of Science', 'Faculty of Science'), ('Faculty of Agriculture', 'Faculty of Agriculture'), ('Faculty of Computer Engineering', 'Faculty of Computer Engineering'), ('Faculty of Mechanical Engineering', 'Faculty of Mechanical Engineering'), ('Faculty of Civil Engineering', 'Faculty of Civil Engineering'), ('Faculty of Science & Technology', 'Faculty of Science & Technology'), ('Faculty of Law', 'Faculty of Law'), ('Faculty of Business Management', 'Faculty of Business Management')], default='', max_length=50)),
                ('reason', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Declined', 'Declined'), ('Accepted', 'Accepted')], default='Pending', max_length=20)),
                ('hr_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nhif', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nssf', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human.employee')),
            ],
        ),
    ]
